services:

  web:
    image: nginx:stable-alpine
    container_name: nginx-network-restricted
    hostname: nginx-network-restricted
    volumes:
      - ./html:/var/www:ro # html files
      - ./configs:/etc/nginx/conf.d # nginx config
    restart: unless-stopped
    expose:
      - 80
    networks:
      - proxy
      - my-internal-network

  php:
    image: php:8-fpm-alpine
    container_name: php-network-restricted
    hostname: php-network-restricted
    volumes:
      - ./html:/var/www # html files
    restart: unless-stopped
    working_dir: /var/www
    expose:
      - 9000
    networks:
      - my-internal-network # no internet access

networks:
  my-internal-network:
    internal: true
  proxy:
    external: true
